apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::196061557907:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-Dwhj2aPEVmfa
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trinee
      userarn: arn:aws:iam::196061557907:user/naresh
      username: naresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-31T02:41:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1309"
  uid: 6ddfdcc4-6843-42b9-aceb-ad0990c342e5