apiVersion: v1
data:
  mapRoles: |
     - rolearn: arn:aws:iam::196061557907:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-lIlR50GGojGx
       groups:
       - system:bootstrappers
       - system:nodes
       username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
      - groups:
        - roboshop-trainee
        userarn: arn:aws:iam::196061557907:user/naresh
        username: naresh
      - groups:
        - roboshop-admin
        userarn: arn:aws:iam::196061557907:user/vinay
        username: vinay
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-31T12:00:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1276"
  uid: 7dbf07f1-b62e-4109-bd0d-eb615ddaf625